// Interface automatically generated by schemas-to-ts

import { Seo } from '../../../../components/page/interfaces/Seo';
import { Seo_Plain } from '../../../../components/page/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/page/interfaces/Seo';

export interface Subpage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    SEO?: Seo;
    contents?: any;
    slug: string;
    locale: string;
    localizations?: { data: Subpage[] };
  };
}
export interface Subpage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  SEO?: Seo_Plain;
  contents?: any;
  slug: string;
  locale: string;
  localizations?: Subpage_Plain[];
}

export interface Subpage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  SEO?: Seo_NoRelations;
  contents?: any;
  slug: string;
  locale: string;
  localizations?: Subpage[];
}

export interface Subpage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  SEO?: Seo_Plain;
  contents?: any;
  slug: string;
  locale: string;
  localizations?: Subpage[];
}
