// Interface automatically generated by schemas-to-ts

import { KeyTopicItem } from '../../internal/interfaces/KeyTopicItem';
import { BaseSettings } from '../../internal/interfaces/BaseSettings';
import { KeyTopicItem_Plain } from '../../internal/interfaces/KeyTopicItem';
import { BaseSettings_Plain } from '../../internal/interfaces/BaseSettings';
import { KeyTopicItem_NoRelations } from '../../internal/interfaces/KeyTopicItem';
import { BaseSettings_NoRelations } from '../../internal/interfaces/BaseSettings';

export interface KeyTopics {
  topics: KeyTopicItem[];
  baseSettings?: BaseSettings;
  headline?: string;
  intro?: any;
}
export interface KeyTopics_Plain {
  topics: KeyTopicItem_Plain[];
  baseSettings?: BaseSettings_Plain;
  headline?: string;
  intro?: any;
}

export interface KeyTopics_NoRelations {
  topics: KeyTopicItem_NoRelations[];
  baseSettings?: BaseSettings_NoRelations;
  headline?: string;
  intro?: any;
}

