// Interface automatically generated by schemas-to-ts

export enum Background {
  Default = 'default',
  Red = 'red',
  RedWave = 'red-wave',}
export enum Container {
  Container = 'container',
  ContainerFluid = 'container-fluid',}

export interface BaseSettings {
  background?: Background;
  container?: Container;
}
export interface BaseSettings_Plain {
  background?: Background;
  container?: Container;
}

export interface BaseSettings_NoRelations {
  background?: Background;
  container?: Container;
}

