// Interface automatically generated by schemas-to-ts

export enum TextAlign {
  Left = 'left',
  Center = 'center',
  Right = 'right',}

export interface BaseTextSettings {
  textAlign?: TextAlign;
}
export interface BaseTextSettings_Plain {
  textAlign?: TextAlign;
}

export interface BaseTextSettings_NoRelations {
  textAlign?: TextAlign;
}

