// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';

export interface KeyTopicItem {
  image: { data: Media };
  content?: any;
  headline?: string;
}
export interface KeyTopicItem_Plain {
  image: Media_Plain;
  content?: any;
  headline?: string;
}

export interface KeyTopicItem_NoRelations {
  image: number;
  content?: any;
  headline?: string;
}

