// Interface automatically generated by schemas-to-ts

export enum Background {
  Default = 'default',
  Red = 'red',
  RedWave = 'red-wave',}
export enum Level {
  H1 = 'h1',
  H2 = 'h2',
  H3 = 'h3',
  H4 = 'h4',}

export interface Headline {
  content: string;
  background: Background;
  level: Level;
}
export interface Headline_Plain {
  content: string;
  background: Background;
  level: Level;
}

export interface Headline_NoRelations {
  content: string;
  background: Background;
  level: Level;
}

