// Interface automatically generated by schemas-to-ts

export enum Background {
  Default = 'default',
  Red = 'red',
  RedWave = 'red-wave',}

export interface Text {
  content?: any;
  background?: Background;
}
export interface Text_Plain {
  content?: any;
  background?: Background;
}

export interface Text_NoRelations {
  content?: any;
  background?: Background;
}

