// Interface automatically generated by schemas-to-ts

export enum FormId {
  Contact = 'contact',
  Workpaper = 'workpaper',}

export interface Form {
  form_id: FormId;
  errorMessage: any;
  successMessage: any;
}
export interface Form_Plain {
  form_id: FormId;
  errorMessage: any;
  successMessage: any;
}

export interface Form_NoRelations {
  form_id: FormId;
  errorMessage: any;
  successMessage: any;
}

