// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';
import { BaseTextSettings } from '../../internal/interfaces/BaseTextSettings';
import { BaseSettings } from '../../internal/interfaces/BaseSettings';
import { Media_Plain } from '../../../common/schemas-to-ts/Media';
import { BaseTextSettings_Plain } from '../../internal/interfaces/BaseTextSettings';
import { BaseSettings_Plain } from '../../internal/interfaces/BaseSettings';
import { BaseTextSettings_NoRelations } from '../../internal/interfaces/BaseTextSettings';
import { BaseSettings_NoRelations } from '../../internal/interfaces/BaseSettings';

export interface Image {
  content?: { data: Media };
  textSettings?: BaseTextSettings;
  baseSettings?: BaseSettings;
  isHeaderImage: boolean;
}
export interface Image_Plain {
  content?: Media_Plain;
  textSettings?: BaseTextSettings_Plain;
  baseSettings?: BaseSettings_Plain;
  isHeaderImage: boolean;
}

export interface Image_NoRelations {
  content?: number;
  textSettings?: BaseTextSettings_NoRelations;
  baseSettings?: BaseSettings_NoRelations;
  isHeaderImage: boolean;
}

